name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.1 # Use the desired Node.js version

      - name: Debug
        run: |
          pwd
          ls -la

      - name: Install dependencies
        run: npm install
        
      - name: Build and package Web application
        run: npx expo export:web
